# (PART\*) PREAMBLE {-}

# Recap: Univariate analyses

We have learned a multitude of analyses that allowed us to interpret ecological data while depicting the effects of _one or multiple_ variables in _one_ response variable.

We can recall the:

1. General Linear Models, from which we used the functions:
  1. `lm()`;
  2. `anova()`;
  3. `t.test()`;
  4. `lmer()`.

2. Generalized Linear Models, where we learned how to apply using:
  1. `glm()` and `glmer()` with several `family()` link functions.

3. Generalized Additive Models, with the: 
  1. `gam()` function.

These models allowed us to ask questions such as:

1. _What are the effects of precipitation and temperature on species richness?_
2. _How does the abundance of microbes change between hosts?_
3. _Do co-occurring fish become more aggressive after being induced to fear?_

However, one may be interested in making inferences from ecological data containing _more than one_ outcome or dependent variable.

This interest may be driven by hypothesis testing and modelling, but also be entirely exploratory.

# Intro: Multivariate analyses

For instance, our research question might be:

1. How does the _bacterial composition_ on maple leaves changes along the elevational gradient?

2. What is the _compositional dissimilarity_ of the bat communities?

3. How _closely-related_ spider local communities are in relation to their _composition_?

In all these cases, the outcome is composed of several variables, _e.g._ usually a sample-by-species or sample-by-environment matrix.

# Setting up our goals

We will now dive into **multivariate statistics**, a tool set that will allow us to address questions requiring the simultaneous observation or analysis of more than one outcome variable.

We will explore certain methods, such as:

1. Association (or dis-similarity) measures and matrices;

2. Classification (or cluster) analysis;

3. Unconstrained ordination;

4. Constrained (or canonical) ordination (in Workshop 10).

Before everything, we will do a little review on **matrix algebra**.