# (PART\*) PRÉAMBULE {-}

# Récapitulatif : Analyses univariées

Nous avons appris une multitude d'analyses qui nous ont permis d'interpréter des données écologiques en décrivant les effets d'une ou de plusieurs variables sur une variable réponse.

Nous pouvons rappeler les :

1. Les modèles linéaires généraux, dont nous avons utilisé les fonctions :
  1. `lm()` ;
  2. `anova()` ;
  3. `t.test()` ;
  4. `lmer()`.

2. Modèles linéaires généralisés, où nous avons appris à les appliquer à l'aide de `t.test()` ; 4. `lmer()` :
  1. `glm()` et `glmer()` avec plusieurs fonctions de liaison `family()`.

3. Modèles Additifs Généralisés, avec les fonctions de liaison `family()` et `glm()` : 
  1. `gam()`.

Ces modèles nous ont permis de poser des questions telles que :

1. Quels sont les effets des précipitations et de la température sur la richesse des espèces ?
2. Comment l'abondance des microbes change-t-elle d'un hôte à l'autre ?
3. Les poissons cooccurrents deviennent-ils plus agressifs après avoir été incités à avoir peur ?

Cependant, il peut être intéressant de faire des déductions à partir de données écologiques contenant "plus d'un" résultat ou d'une variable dépendante.

Cet intérêt peut être motivé par la vérification d'hypothèses et la modélisation, mais il peut aussi être entièrement exploratoire.

# Intro : Analyses multivariées

Par exemple, notre question de recherche pourrait être la suivante

1. Comment la _composition bactérienne_ des feuilles d'érable change-t-elle le long du gradient d'altitude ?

2. Quelle est la _dissemblance compositionnelle_ des communautés de chauves-souris ?

3. Quelle est la _proximité_ des communautés locales d'araignées par rapport à leur _composition_ ?

Dans tous ces cas, le résultat est composé de plusieurs variables, _par exemple_ habituellement une matrice échantillon par espèce ou échantillon par environnement.

# Définir nos objectifs

Nous allons maintenant nous plonger dans les **statistiques multivariées**, un ensemble d'outils qui nous permettra d'aborder des questions nécessitant l'observation ou l'analyse simultanée de plus d'une variable de résultat.

Nous explorerons certaines méthodes, telles que:

1. Mesures et matrices d'association (ou de dissemblance) ;

2. L'analyse de classification (ou de regroupement) ;

3. Ordination sans contrainte ;

4. Ordination contrainte (ou canonique) (dans l'atelier 10).

Avant tout, nous allons faire un petit rappel sur l'algèbre des matrices.